services:
  web:
    image: php:8.0-apache
    container_name: php_web
    platform: linux/amd64
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: toko_db
    command: >
      bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
               docker-php-ext-install pdo pdo_mysql &&
               apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql_db
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toko_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db_toko.sql:/docker-entrypoint-initdb.d/db_toko.sql

volumes:
  db_data:
